# This script generates the figures and the numerical results included in the CMP
# 406 text. It assumes that all of the data has been generated by the L0 scripts 
# and is located in the data directory. 

# 0. Set Up --------------------------------------------------------------------
library(dplyr)
library(ggplot2)
library(ggpmisc)
library(tidyr)
library(scales)
library(here)
library(ggpp)
library(patchwork)


# Important note, that the specific hector version does not matter here since 
# we are just using the helper functions. 
library(hector) 

# Define the location where to write the files out to 
MAIN_FIGS <- here::here("figs")
SUP_FIGS  <- here::here("figs", "supplemental_figs")
dir.create(MAIN_FIGS, showWarnings = FALSE)
dir.create(SUP_FIGS, showWarnings = FALSE)

# Figure settings 
theme_set(theme_bw() + theme(legend.title = element_blank()))
ggplot_colors <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, c = 100, l = 65)[1:n]
}

my_colors <- ggplot_colors(n = 2)
COLOR_SCHEME <- c("old" = my_colors[1], "new" = my_colors[2], 
                  "V3.2.0" = my_colors[1], "V3.5.0" = my_colors[2], 
                  "cmip7" = "black", 
                  "BerkeleyEarthGlobal" = "black", 
                  "HadCRUT5Global" = "black", 
                  "NOAAGlobalTempGlobal" = "black")
# Define the GCAM color palette 
gcam_color_palette <- ggplot_colors(n = 6)
GCAM_COLOR_SCHEME <- c(gcam_color_palette)
names(GCAM_COLOR_SCHEME) <- c(paste0("GCAM_SSP", 1:5), "Reference")
GCAM_COLOR_SCHEME <- c(GCAM_COLOR_SCHEME, "pre-gcam hist." = "black")

# Global options for plotting 
TYPE <- "png"
WIDTH <- 10 
HEIGHT <- 8

# Options for cleaning up the environment 
CLEAN_UP <- FALSE


# 1. Historical Input Comparison -----------------------------------------------
## 1A. Load Data  ---------------------------------------------------------------
here("inputs", "dev") %>% 
  list.files(pattern = "default_inputs|gcam_emissions", full.names = TRUE) %>% 
  lapply(function(f){
    
    read.csv(f, comment.char = ";") %>% 
      pivot_longer(-Date, names_to = "variable") %>% 
      rename(year = Date) 
    
  }) %>% 
  bind_rows %>% 
  mutate(source = "new") -> 
  new_inputs

here("inputs", "old") %>% 
  list.files(pattern = "default_emissions|gcam_emissions", full.names = TRUE) %>% 
  lapply(function(f){
    
    read.csv(f, comment.char = ";") %>% 
      pivot_longer(-Date, names_to = "variable") %>% 
      rename(year = Date) 
    
  }) %>% 
  bind_rows %>% 
  mutate(source = "old") -> 
  old_inputs

# Manually add the natural emissions that were hard coded in the older 
# gcam-hector implementation. 
bind_rows(data.frame(year = unique(old_inputs$year), 
                     variable = NATURAL_CH4(), 
                     value = 335, 
                     source = "old"), 
          data.frame(year = unique(old_inputs$year), 
                     variable = NAT_EMISSIONS_N2O(), 
                     value = 9.7, 
                     source = "old"), 
          data.frame(year = unique(old_inputs$year), 
                     variable = "RF_misc", 
                     value = 0, 
                     source = "old"), 
          old_inputs) -> 
  old_inputs


# Combine the inputs into a single data frame
bind_rows(new_inputs, old_inputs) -> 
  inputs_df

## 1B. Helper Functions  --------------------------------------------------------

# Helper function that plots the inputs against one another 
# Args 
#   data: data frame of inputs 
#   variables: vector of variable names 
#   write_to: str directory where to save the results to 
#   type: str that determines the figure file type that is being saved, default set to global option
#   w: int determines the width of the figure saved, default set to global option
#   h: int determines the height of the figure saved, default set to global option
# Returns: list of ggplot objects and write figures out to disk 
plot_inputs_fxn <- function(data, variables, write_to, 
                            type = TYPE, w = WIDTH, h = HEIGHT){
  
  # Calculate the RMSE between the inputs... 
  data %>%
    # Subset the data so that it only includes the variables of interest 
    filter(variable %in% variables) %>% 
    pivot_wider(names_from = source, values_from = value) %>%
    na.omit %>% 
    mutate(SE = (new - old)^2) %>%
    summarise(RMSE = sqrt(mean(SE)), .by = c(variable)) %>%
    mutate(RMSE = signif(RMSE, digits = 3)) %>% 
    mutate(units = getunits(variable)) -> 
    RMSE_df
  
  
  # Make a list to save all the pots to 
  plots <- vector("list", length(variables)) # preallocate list
  
  # For each variable make a line plot and include a 
  for (v in variables){
    print(v)
    
    # Subset the RMSE data frame 
    RMSE_df %>% 
      filter(variable == v) -> 
      RMSE_df_to_plot
    
    # subset and format the RMSE results to be included in the plot. 
    tibble(x = Inf, 
           y = -Inf, 
           label = list(RMSE_df_to_plot)) -> 
      RMSE_tib
    
    data %>%
      filter(variable == v) -> 
      to_plot 
    
    ggplot() +
      geom_line(data = to_plot, aes(year, value, color = source, linetype = source)) +
      labs(x = NULL, title = "GCAM-Hector Input Comparison", subtitle = v, y = getunits(v)) + 
      theme(legend.title = element_blank(), legend.position = "bottom") +
      geom_table(data = RMSE_tib, aes(x = x, y = y, label = label),
                 hjust = 1, vjust = 0) + 
      scale_color_manual(values = COLOR_SCHEME) -> 
      p 
    
    fname <- file.path(write_to, "inputs", paste0("inputs_", v, ".", type))
    ggsave(plot = p, filename = fname, width = w, height = h)
    
    plots[[v]] <- p
  }
  
  return(plots)
  
}


## 1C. Plot Inputs  -------------------------------------------------------------

# Plot all of the variables! 
all_plots <- plot_inputs_fxn(data = inputs_df, 
                             variables = unique(inputs_df$variable), 
                             write_to = SUP_FIGS)

# There are some specific plots that we know we want to see in the main CMP 
# so let's modify as necessary and save there.. 
fname <- file.path(MAIN_FIGS,  paste0("SV_inputs.", TYPE))
ggsave(plot = all_plots$SV, filename = fname, width = WIDTH, height = HEIGHT)

# Add the NCH4 benchmarks
prather <- data.frame(year =  unique(inputs_df$year), value = 202, sd = 0, name = "Prather 2012")
fair <- data.frame(year =   unique(inputs_df$year), lower = 140, upper = 220, name = "Fair 2018")

benchmarks <- rbind(prather)

all_plots$CH4N + 
  geom_ribbon(data = fair, aes(year, ymin =lower, ymax = upper, fill = name), alpha = 0.2) + 
  geom_point(data = benchmarks, aes(year, value, fill = name)) + 
  scale_fill_grey() -> 
  p

fname <- file.path(MAIN_FIGS,  paste0("natural_CH4.", TYPE))
ggsave(plot =  p, filename = fname, width = WIDTH, height = HEIGHT)

## 1D. Clean Up  -------------------------------------------------------------
if(CLEAN_UP){
  remove(c(all_plots, specific_inputs, inputs_df, new_inputs, old_inputs, plot_inputs_fxn))
}

# 2. Continuity of Emissions from pre GCAM to GCAM generated -------------------
# The purpose of these plots is to take a look at the continuity of emissions 
# when hector moves from the pre gcam driven to the gcam driven input emissions. 
## 2A. Load Data ---------------------------------------------------------------

# Start by loading the pre gcam historical emissions... 
here("inputs", "dev") %>% 
  list.files(pattern = "gcam_emissions", full.names = TRUE) %>% 
  lapply(function(f){
    
    read.csv(f, comment.char = ";") %>% 
      pivot_longer(-Date, names_to = "variable") %>% 
      rename(year = Date) 
    
  }) %>% 
  bind_rows %>% 
  mutate(source = "pre-gcam hist") -> 
  pre_gcam_hist

# Now let's load the emissions from the new GCAM results 
here("data") %>% 
  list.files(pattern = "GCAM_new_rslts.csv", full.names = TRUE) %>% 
  read.csv %>% 
  filter(variable %in% pre_gcam_hist$variable) -> 
  gcam_emissions

## 2B. Helper Functions --------------------------------------------------------

# Helper function that plots the pre gcam historical emissions against teh 
# GCAM emissions that drive hector post 2023. 
# Args 
#   hist_data: data frame of the pre gcam historical inputs
#   gcam_data: data frame of the GCAM emissions 
#   variables: vector of variable names 
#   write_to: str directory where to save the results to 
#   type: str that determines the figure file type that is being saved, default set to global option
#   w: int determines the width of the figure saved, default set to global option
#   h: int determines the height of the figure saved, default set to global option
# Returns: list of ggplot objects and write figures out to disk 
plot_emiss_transition <- function(hist_data, 
                                  gcam_data, 
                                  variables, 
                                  write_to, 
                                  type = TYPE, 
                                  w = WIDTH,
                                  h = HEIGHT){
  
  plots <- vector("list", length(variables)) # preallocate list
  for(v in variables){
    
    print(v)
    
    hist_data %>% 
      filter(variable == v) %>% 
      filter(year >= 1975) -> 
      hist_to_plot
    
    gcam_data %>% 
      filter(variable == v) %>% 
      filter(year <= 2050) -> 
      gcam_to_plot
    
    # Make the plot! 
    ggplot() + 
      geom_vline(xintercept = 2023, color = "grey") + 
      geom_line(data = hist_to_plot, aes(year, value, color = "pre-gcam hist.")) +
      geom_line(data = gcam_to_plot, aes(year, value, color = scenario), alpha = 0.25) + 
      geom_point(data = gcam_to_plot, aes(year, value, color = scenario)) + 
      labs(title = "Transition of historical to GCAM emissions", 
           subtitle = v, 
           y = getunits(v), 
           x = NULL, caption = "transition from historical to GCAM emissions in 2023") + 
      scale_color_manual(values = GCAM_COLOR_SCHEME) -> 
      p
    
    fname <- file.path(write_to, "transition", paste0("trans_", v, ".", type))
    ggsave(plot = p, filename = fname, width = w, height = h)
    
    plots[[v]] <- p
    
  }
  
  return(plots)
  
}

## 2C. Plots  ------------------------------------------------------------------
# Plot all of the transitions from pre gcam to the gcam emissions 
continutiy_plots <- plot_emiss_transition(hist_data = pre_gcam_hist, 
                                          gcam_data = gcam_emissions, 
                                          variables = unique(pre_gcam_hist$variable), 
                                          write_to = SUP_FIGS)

## 2D. Clean Up  ---------------------------------------------------------------
if(CLEAN_UP){
  remove(c(gcam_emissions, plot_emiss_transition, pre_gcam_hist))
}

# 3. GCAM Hector Results Comparison --------------------------------------------
## 3A. Load Data  --------------------------------------------------------------

# Now let's load the non GCAM emissions for comparison. 
here("data") %>% 
  list.files(pattern = "GCAM_new_rslts|GCAM_old_rslts", full.names = TRUE) %>% 
  lapply(read.csv) %>% 
  bind_rows %>% 
  filter(!grepl(pattern = "emiss|uptake", x = variable)) %>%
  na.omit -> 
  gcam_rslsts

## 3B. Load Data  --------------------------------------------------------------

# Helper function that plots the GCAM results against one another
# Args 
#   data: data frame of the GCAM results
#   variables: vector of variable names 
#   write_to: str directory where to save the results to 
#   type: str that determines the figure file type that is being saved, default set to global option
#   w: int determines the width of the figure saved, default set to global option
#   h: int determines the height of the figure saved, default set to global option
# Returns: list of ggplot objects and write figures out to disk 
plot_gcam_fxn <- function(data, variables, write_to, 
                          type = TYPE, w = WIDTH, h = HEIGHT){
  
  
  # Calculate the RMSE between the inputs... 
  data %>%
    # Subset the data so that it only includes the variables of interest 
    filter(variable %in% variables) %>% 
    pivot_wider(names_from = version, values_from = value) %>%
    na.omit %>% 
    mutate(SE = (new - old)^2) %>%
    summarise(RMSE = sqrt(mean(SE)), .by = c(variable, scenario)) %>%
    mutate(RMSE = signif(RMSE, digits = 3)) -> 
    RMSE_df
  
  
  # Make a list to save all the pots to 
  plots <- vector("list", length(variables)) # preallocate list
  
  # For each variable make a line plot and include a 
  for (v in variables){
    print(v)
    
    # Subset the RMSE data frame 
    RMSE_df %>% 
      filter(variable == v) %>%  
      mutate(label = paste0("RMSE = ", RMSE)) %>%
      mutate(x = -Inf, y = Inf) %>%       # top‑left of each facet
      select(scenario, x, y, label) -> 
      RMSE_tib
    
    data %>%
      filter(variable == v) -> 
      to_plot 
    
    ggplot() +
      geom_line(data = to_plot, aes(year, value, color = version, linetype = version)) +
      labs(x = NULL, title = "GCAM-Hector Comparison", subtitle = v, y = getunits(v)) + 
      theme(legend.title = element_blank(), legend.position = "bottom") +
      geom_text(data = RMSE_tib, aes(x = x, y = y, label = label), 
                hjust = -0.1, vjust = 1.2) + 
      scale_color_manual(values = COLOR_SCHEME) + 
      facet_wrap("scenario") -> 
      p 
    
    fname <- file.path(write_to, "gcam", paste0("gcam_", v, ".", type))
    ggsave(plot = p, filename = fname, width = w, height = h)
    
    plots[[v]] <- p
  }
  
  return(plots)
  
} 

## 3C. Plot GCAM  -------------------------------------------------------------

# Plot all of the variables! 
all_plots <- plot_gcam_fxn(data = gcam_rslsts, 
                           variables = unique(gcam_rslsts$variable), 
                           write_to = SUP_FIGS)

## 3D. Clean Up  ---------------------------------------------------------------
if(CLEAN_UP){
  remove(c(gcam_rslsts, plot_gcam_fxn))
}



# 4. Stand Alone Hector Comparison ---------------------------------------------
# Compare the stand alone hector results against one another, this is a good 
# way to sense if/how the hector behavior has changed with the different dev/params.
## 4A. Load Data  ---------------------------------------------------------------

data.frame(rslts = list.files(here("data"), pattern = "v32|v35", full.names = TRUE)) %>% 
  filter(!grepl(pattern = "AR6", x = rslts)) %>% 
  pull(rslts) %>% 
  lapply(function(f){
    read.csv(f) %>% 
      mutate(year = as.integer(gsub(pattern = "X", replacement = "", x = year)))
  }) %>%
  bind_rows %>% 
  distinct -> 
  hector_rslts

## 4B. Helper Functions  --------------------------------------------------------

# Helper function that plots the inputs against one another 
# Args 
#   data: data frame of hector results 
#   variables: vector of variable names 
#   write_to: str directory where to save the results to 
#   tag: str indicating the scenario type or what not is being saved, a unique identifier
#   type: str that determines the figure file type that is being saved, default set to global option
#   w: int determines the width of the figure saved, default set to global option
#   h: int determines the height of the figure saved, default set to global option
# Returns: list of ggplot objects and write figures out to disk 
plot_hector_fxn <- function(data, variables, write_to, tag,
                            type = TYPE, w = WIDTH, h = HEIGHT){
  
  # Calculate the RMSE between the inputs... 
  data %>%
    # Subset the data so that it only includes the variables of interest 
    filter(variable %in% variables) %>% 
    distinct %>% 
    pivot_wider(names_from = version, values_from = value) %>%
    na.omit %>% 
    mutate(SE = (`V3.2.0` - V3.5.0)^2) %>% 
    summarise(RMSE = sqrt(mean(SE)), .by = c(variable, units, scenario)) %>%
    mutate(RMSE = signif(RMSE, digits = 3)) -> 
    RMSE_df
  
  
  # Make a list to save all the pots to 
  plots <- vector("list", length(variables)) # preallocate list
  
  # For each variable make a line plot and include a 
  for (v in variables){
    # v <- variables[1]
    print(v)
    
    # Subset the RMSE data frame 
    RMSE_df %>% 
      filter(variable == v) -> 
      RMSE_df_to_plot
    
    # subset and format the RMSE results to be included in the plot. 
    tibble(x = Inf, 
           y = -Inf, 
           label = list(RMSE_df_to_plot)) -> 
      RMSE_tib
    
    data %>%
      filter(variable == v) -> 
      to_plot 
    
    ggplot() +
      geom_line(data = to_plot,
                aes(year, value, color = version, linetype = version, 
                    group = interaction(scenario, version))) +
      labs(x = NULL, title = "Stand Alone Hector Comparison",
           subtitle = v,
           y = RMSE_df_to_plot$units[1]) +
      theme(legend.title = element_blank(),
            legend.position = "bottom") +
      scale_color_manual(values = COLOR_SCHEME) -> 
      p1
    
    # RMSE table
    ggplot() +
      geom_table(
        data = RMSE_tib,
        aes(x = 0, y = 1, label = label),
        hjust = 0,
        vjust = 1
      ) +
      xlim(0, 1) +
      ylim(0, 1) +
      theme_void() +
      theme(
        plot.margin = margin(0, 0, 0, 0)
      ) + 
      coord_cartesian(clip = "off") -> 
      p2
    
    
    p1 | p2 +
      plot_layout(widths = c(1, 0.15)) -> 
      p
    
    fname <- file.path(write_to, "hector", paste0("hector_", tag, "_", v, ".", type))
    ggsave(plot = p, filename = fname, width = w, height = h)
    
    plots[[v]] <- p
  }
  
  return(plots)
  
}


## 4C. All Plots  --------------------------------------------------------------

# For the gcam history scenario let's plot all of the results 
hector_rslts %>% 
  filter(scenario ==  "gcam-hist") %>% 
  plot_hector_fxn(data = ., 
                  variables = unique(.$variable), 
                  write_to = SUP_FIGS, 
                  tag = "gcamhist") -> 
  gcamhist_plots

# For all the SSP scenarios 
hector_rslts %>% 
  filter(grepl(pattern = "ssp", scenario)) %>%  
  plot_hector_fxn(data = ., 
                  variables = unique(.$variable), 
                  write_to = SUP_FIGS,
                  tag = "ssp") -> 
  ssp_plots

# For all the idealized scenarios, note that for these experiments we 
# only care about a handful of variables...
hector_rslts %>% 
  filter(scenario %in% c("1pctCO2", "abruptx2CO2", "abruptx4CO2")) %>% 
  filter(variable %in% c("global_tas", "RF_tot")) %>% 
  plot_hector_fxn(data = ., 
                  variables = unique(.$variable), 
                  write_to = SUP_FIGS,
                  tag = "ideal") -> 
  ideal_plots


## 4D. Main CMP Plots  ---------------------------------------------------------
# These are some figures that need some addition tweaks (external benchmarks)
# before they can be saved as a main plot. 

# TAU OH 

# Some benchmarks pulled from the literature
data.frame(year = 2000,
           value = 9.8,
           sd = 1.6) %>%
  mutate(min = value - sd,
         max = value + sd,
         name = "Volugarakis_2013") ->
  Volugarakis_2013

data.frame(year = c(1850, 1980, 2000),
           value = c(10.1, 10.2, 9.7),
           sd = c(1.7, 1.7, 1.5)) %>%
  mutate(min = value - sd,
         max = value + sd,
         name = "Naik_2013") ->
  Naik_2013

tau_oh_benchmarks <- rbind(Volugarakis_2013, Naik_2013)

plots <- patchwork:::as.list.patchwork(gcamhist_plots$TAU_OH)

plots[[1]] + 
  geom_errorbar(data = tau_oh_benchmarks, 
                aes(x = year, ymin = min, ymax = max), color = "darkgrey") +
  geom_point(data = tau_oh_benchmarks, 
             aes(year, value, color = name), size = 2) + 
  labs(subtitle = "gcam-hist tau OH", 
       caption = "error bars from Stevenson et al 2020") -> 
  p

fname <- file.path(MAIN_FIGS,  paste0("hector_tauOH_wbench.", TYPE))
ggsave(plot = p, filename = fname, width = WIDTH, height = HEIGHT)


# 5. Observations Comparison ---------------------------------------------------
## 5A. Define Helper Fxns & Load Data ------------------------------------------

# Ocean heat content constants
OCEAN_AREA <- 5100656e8 * (1 - 0.29) # The total area of the ocean
W_TO_ZJ <- 3.155693e-14              # Watts to ZJ

# Since the temperatures are all relative to a baseline this helper function
# normalize the data to help facilitate the comparison of the data.
# Args
#   data: data frame of global temperature
#   yrs: vector of base period years
# Returns: data frame of the normalized temperature data
normalize_data_fxn <- function(data, yrs){
  
  # confirm that the df has the required columns and that there is
  # data for all the base period years.
  req_names <- c("year", "value")
  stopifnot(all(req_names %in% names(data)))
  #stopifnot(all(yrs %in% data$year))
  
  # format the units label
  units <- paste("relative to", paste(range(yrs), collapse = "-"))
  
  # the reference temperature
  data %>%
    filter(year %in% yrs) %>%
    pull(value) %>%
    mean ->
    ref_value
  
  # normalize to the reference value
  data %>%
    mutate(value = value - ref_value,
           units = units) ->
    out
  
  return(out)
}


# Fetch the relevant Hector results for the data comparison,
# make sure that they are in the correct units.
# Args
#   hc: active hector core that has completed a run or set to NULL
#   comp: data.frame of the observations to use in the comparison
#   hector_out: data.frame of hector results or set to NULL, default set to NULL
# Returns: data.frame of Hector results in the correct units for comparison
fetchvars_4comparison <- function(hc, comp, hector_out = NULL){
  
  null_length <- sum(c(is.null(hc), is.null(hector_out)))
  stopifnot(null_length == 1)
  
  hector_ch4 <- hector_n2o <- NULL
  
  # If the object read in is a hector core use fetchvars to get the
  # equalivent to compare with observations otherwise extract from
  # a hector output data frame.
  if(class(hc)[[1]] == "hcore"){
    
    # Make sure that the hector core has been run!
    stopifnot(!hc[["strtdate"]] == hc[["enddate"]])
    
    yrs <- min(comp$year):max(comp$year)
    
    fetchvars(core = hc,
              dates = yrs,
              vars = CONCENTRATIONS_CO2()) ->
      hector_co2
    
    fetchvars(core = hc,
              dates = yrs,
              vars = GMST()) %>%
      normalize_data_fxn(yrs = 1951:1980) %>%
      mutate(units = "relative to 1951-1980") ->
      hector_gmst
    
    fetchvars(core = hc,
              dates = yrs,
              vars = HEAT_FLUX()) %>%
      # Convert from heat flux to OHC that can be used
      mutate(value = value * OCEAN_AREA * W_TO_ZJ) %>%
      mutate(value = cumsum(value),
             variable = "OHC") %>%
      # Normalize to the correct reference period.
      normalize_data_fxn(yrs = 2005:2014) %>%
      mutate(units = "2005-2014 base period") ->
      hector_ohc
    
    
    if (CONCENTRATIONS_CH4() %in% comp$variable) {
      fetchvars(core = hc,
                dates = yrs,
                vars = CONCENTRATIONS_CH4()) ->
        hector_ch4
      
    }
    
    
    if (CONCENTRATIONS_N2O() %in% comp$variable) {
      fetchvars(core = hc,
                dates = yrs,
                vars = CONCENTRATIONS_N2O()) ->
        hector_n2o
      
    }
    
    
    
    
    
  } else if(is.data.frame(hector_out)){
    
    
    yrs <- min(comp$year):max(comp$year)
    
    
    hector_out %>%
      filter(year %in% yrs, variable == CONCENTRATIONS_CO2()) ->
      hector_co2
    
    hector_out %>%
      filter(year %in% yrs, variable == GMST()) %>%
      normalize_data_fxn(yrs = 1951:1980) %>%
      mutate(units = "relative to 1951-1980") ->
      hector_gmst
    
    hector_out %>%
      filter(year %in% yrs, variable == HEAT_FLUX()) %>%
      # Convert from heat flux to OHC that can be used
      mutate(value = value * OCEAN_AREA * W_TO_ZJ) %>%
      mutate(value = cumsum(value),
             variable = "OHC") %>%
      # Normalize to the correct reference period.
      normalize_data_fxn(yrs = 2005:2014) %>%
      mutate(units = "2005-2014 base period") ->
      hector_ohc
    
    if (CONCENTRATIONS_CH4() %in% comp$variable) {
      hector_out %>%
        filter(year %in% yrs, variable == CONCENTRATIONS_CH4()) ->
        hector_ch4
      
    }
    
    
    if (CONCENTRATIONS_N2O() %in% comp$variable) {
      hector_out %>%
        filter(year %in% yrs, variable == CONCENTRATIONS_N2O()) ->
        hector_n2o
      
    }
    
    
    
  }
  
  
  
  bind_rows(hector_co2,
            hector_gmst,
            hector_ohc,
            hector_n2o,
            hector_ch4) %>%
    select(scenario, year, variable, hector = value, units) ->
    out
  
  return(out)
}

# The variables we would like to compare with are [CO2], [CH4], [N2O], gmst, OHC 
VARS <- c(CONCENTRATIONS_CO2(), CONCENTRATIONS_N2O(), CONCENTRATIONS_CH4(), GMST(), HEAT_FLUX())

# Load the observational data sets... 
here("data", "auxiliary") %>% 
  list.files(pattern = "^C.*.csv", full.names = TRUE) %>% 
  lapply(read.csv) %>% 
  bind_rows -> 
  obs_data

# Load the historical GCAM data 
here("data") %>% 
  list.files(pattern = "v320_rslts|v350_rslts", full.names = TRUE) %>% 
  lapply(function(f){
    read.csv(f) %>% 
      mutate(year = as.integer(year)) %>% 
      filter(scenario == "gcam-hist" & variable %in% VARS) -> 
      d 
    
    fetchvars_4comparison(hc = NULL, comp = obs_data, hector_out =  d) %>% 
      mutate(version = d$version[1]) %>% 
      rename(value = hector) -> 
      out 
    return(out)
      
  }) %>%
  bind_rows %>% 
  distinct -> 
  hector_hist

# Calculate the RMSE between the fits and the observations... 
hector_hist %>% 
  distinct %>% 
  left_join(select(obs_data, year, obs = value, variable)) %>% 
  na.omit %>%
  mutate(SE = (value - obs)^2) %>% 
  summarise(RMSE = sqrt(mean(SE)), .by = c(scenario, variable, units, version)) %>%
  mutate(RMSE = signif(RMSE, digits = 3)) -> 
  RMSE_df


## 5B. GHGs  -------------------------------------------------------------------
# Let's start by comparing the GHG concentrations with observations... 
hector_hist %>% 
  filter(variable %in% c(CONCENTRATIONS_CH4(), 
                         CONCENTRATIONS_CO2(),
                         CONCENTRATIONS_N2O())) %>% 
  split(.$variable) %>% 
  lapply(FUN = function(hector_data){
    
    obs_data %>%  
      filter(variable == unique(hector_data$variable)) -> 
      obs_to_plot
    
    RMSE_df %>%  
      filter(variable == unique(hector_data$variable)) %>% 
      select(-scenario) -> 
      RMSE_to_plot
    
    tibble(x = -Inf, 
           y = Inf, 
           label = list(RMSE_to_plot)) -> 
      RMSE_tib
    
    ggplot() + 
      geom_line(data = obs_to_plot, aes(year, value, color = "cmip7")) + 
      geom_line(data = hector_data, aes(year, value, color = version, 
                                        linetype = version)) + 
      scale_color_manual(values = COLOR_SCHEME) + 
      labs(x = NULL, y = hector_data$units[1]) + 
      theme(legend.title = element_blank(), legend.position = "bottom") +
      geom_table(data = RMSE_tib, aes(x = x, y = y, label = label),
                 hjust = 0, vjust = 1) + 
      labs(title = paste0(hector_data$variable[1], 
                          " Comparison with Observations"), 
           caption = "RMSE between hector & obs") -> 
      p; p 
    
    fname <- file.path(SUP_FIGS, "obs", paste0("obs_", obs_to_plot$variable[1], ".", TYPE))
    ggsave(plot = p, filename = fname, width = WIDTH, height = HEIGHT)
    return(p)
  }) -> 
  ghg_obs_plots



## 5C. GMST  -------------------------------------------------------------------
# Let's start by comparing the GHG concentrations with observations... 
hector_hist %>% 
  filter(variable == "gmst") %>% 
  filter(year >= 1845) -> 
  hector_data

obs_data %>%  
  filter(variable == unique(hector_data$variable)) -> 
  obs_to_plot

RMSE_df %>%  
  filter(variable == unique(hector_data$variable)) %>% 
  select(-scenario, -units) -> 
  RMSE_to_plot

tibble(x = -Inf, 
       y = Inf, 
       label = list(RMSE_to_plot)) -> 
  RMSE_tib

ggplot() + 
  geom_line(data = obs_to_plot, aes(year, value, color = "cmip7")) + 
  geom_ribbon(data = obs_to_plot, aes(year, ymin = lower, ymax = upper, fill = "cmip7"), alpha = 0.5) + 
  geom_line(data = hector_data, aes(year, value, color = version, 
                                    linetype = version)) + 
  scale_color_manual(values = COLOR_SCHEME) + 
  scale_fill_manual(values = COLOR_SCHEME) + 
  labs(x = NULL, y = hector_data$units[1]) + 
  theme(legend.title = element_blank(), legend.position = "bottom") +
  geom_table(data = RMSE_tib, aes(x = x, y = y, label = label),
             hjust = 0, vjust = 1) + 
  labs(title = paste0(hector_data$variable[1], 
                      " Comparison with Observations"), 
       caption = "RMSE between hector & obs") -> 
  temp_obs_plots; temp_obs_plots

fname <- file.path(SUP_FIGS, "obs", paste0("obs_", obs_to_plot$variable[1], ".", TYPE))
ggsave(plot = temp_obs_plots, filename = fname, width = WIDTH, height = HEIGHT)



## 5D. heatflux  ---------------------------------------------------------------
# Let's start by comparing the heatflux
hector_hist %>% 
  filter(variable == "OHC") %>% 
  filter(year >= 1945) -> 
  hector_data

obs_data %>%  
  filter(variable == unique(hector_data$variable)) -> 
  obs_to_plot

RMSE_df %>%  
  filter(variable == unique(hector_data$variable)) %>% 
  select(-scenario, -units) -> 
  RMSE_to_plot

tibble(x = -Inf, 
       y = Inf, 
       label = list(RMSE_to_plot)) -> 
  RMSE_tib

ggplot() + 
  geom_line(data = obs_to_plot, aes(year, value, color = "cmip7")) + 
  geom_ribbon(data = obs_to_plot, aes(year, ymin = lower, ymax = upper, fill = "cmip7"), alpha = 0.5) + 
  geom_line(data = hector_data, aes(year, value, color = version, 
                                    linetype = version)) + 
  scale_color_manual(values = COLOR_SCHEME) + 
  scale_fill_manual(values = COLOR_SCHEME) + 
  labs(x = NULL, y = hector_data$units[1]) + 
  theme(legend.title = element_blank(), legend.position = "bottom") +
  geom_table(data = RMSE_tib, aes(x = x, y = y, label = label),
             hjust = 0, vjust = 1) + 
  labs(title = paste0(hector_data$variable[1], 
                      " Comparison with Observations"), 
       caption = "RMSE between hector & obs") -> 
  ohc_obs_plots; ohc_obs_plots

fname <- file.path(SUP_FIGS, "obs", paste0("obs_", obs_to_plot$variable[1], ".", TYPE))
ggsave(plot = ohc_obs_plots, filename = fname, width = WIDTH, height = HEIGHT)

# 6. AR6 Comparison ------------------------------------------------------------
## 6A. Load Data  ---------------------------------------------------------------
# Import the hector results that will be compared with the AR6 benchmarks values. 
data.frame(rslts = list.files(here("data"), pattern = "v32|v35", full.names = TRUE)) %>% 
  filter(grepl(pattern = "AR6", x = rslts)) %>% 
  pull(rslts) %>% 
  lapply(read.csv) %>% 
  bind_rows %>% 
  distinct %>% 
  mutate(version = paste0("V", version)) -> 
  hector_rslts

# Load the benchmarking data, there are two different versions of the AR6 data 
# the assessed ranges and then also the individual SCMs. 
here("data", "auxiliary") %>% 
  list.files("ar6_scms.csv", full.names = TRUE) %>% 
  read.csv() -> 
  ar6_scm_benchmarks

here("data", "auxiliary") %>% 
  list.files("ar6.csv", full.names = TRUE) %>% 
  read.csv() -> 
  ar6_ipcc_benchmarks

# Plot aesthetics 
JW <- 0.15
COLORS.BENCHMARKS <- c(COLOR_SCHEME ,"ipcc ar6" = "black", "scms from ar6" = "grey", 
                       "FaIRv1.6.2" = "blue", "MAGICC7" = "purple")


## 6B. Emergent Metrics  -------------------------------------------------------

# Key metrics to compare 
VARS <- c("tcre", "tcr")

hector_rslts %>% 
  filter(variable %in% VARS) -> 
  hec_key

ar6_scm_benchmarks %>% 
  mutate(variable = tolower(variable)) %>% 
  filter(variable %in% VARS) -> 
  scm_key

ar6_ipcc_benchmarks %>% 
  mutate(variable = tolower(variable)) %>% 
  filter(variable %in% VARS) -> 
  ipcc_key

ggplot() + 
  geom_errorbar(data = ipcc_key,
                aes(variable, ymin = min, ymax = max),
                width=.2, alpha = 0.5) +
  geom_point(data = hec_key, aes(variable, value, color = version),
             position = position_jitter(height = 0, width = 0)) + 
  geom_point(data = scm_key, aes(variable, value, color = source),
             shape = 4, position = position_jitter(height = 0, width = JW)) +
  geom_point(data = ipcc_key, aes(variable, value, color = "ipcc ar6"), shape = 4) +
  labs(y = NULL, x = NULL, title = "Key Metrics") + 
  scale_color_manual(values = COLORS.BENCHMARKS) + 
  theme(legend.title = element_blank()) -> 
  p; p


fname <- file.path(file.path(SUP_FIGS, "AR6"),  paste0("AR6_emergent_metrics.", TYPE))
ggsave(plot = p, filename = fname, width = WIDTH, height = HEIGHT)


## 6C. Historical Values  ------------------------------------------------------
# Historical Values
VARS <- c("OHC", "RF_CH4", "wmghg RF",  "total aerosol RF", "hist. warming")

hector_rslts %>% 
  filter(variable %in% VARS) -> 
  hec_his

ar6_scm_benchmarks %>% 
  filter(variable %in% VARS) -> 
  scm_his

ar6_ipcc_benchmarks %>% 
  filter(variable %in% VARS) -> 
  ipcc_his

ggplot() + 
  geom_errorbar(data = ipcc_his,
                aes(variable, ymin = min, ymax = max),
                width=.2, alpha = 0.5) +
  geom_point(data = hec_his, aes(variable, value, color = version), alpha = 0.75) + 
  geom_point(data = scm_his, aes(variable, value, color = source),
             shape = 4, position = position_jitter(height = 0, width = JW)) +  
  geom_point(data = ipcc_his, aes(variable, value, color = "ipcc ar6"), shape = 4) +
  labs(y = NULL, x = NULL, title = "Historic Metrics") + 
  scale_color_manual(values = COLORS.BENCHMARKS) + 
  theme(legend.title = element_blank()) + 
  facet_wrap("variable", scales = "free") -> 
  p; p

fname <- file.path(file.path(SUP_FIGS, "AR6"),  paste0("AR6_hist_.", TYPE))
ggsave(plot = p, filename = fname, width = WIDTH, height = HEIGHT)

## 2C. Warming Values  ------------------------------------------------------

VARS <- c(GLOBAL_TAS())

hector_rslts %>% 
  filter(variable %in% VARS) %>%  
  filter(scenario %in% c("ssp119", "ssp126", "ssp245", "ssp370", "ssp585")) -> 
  hec_warm

ar6_scm_benchmarks %>% 
  filter(variable %in% VARS) -> 
  scm_warm

ar6_ipcc_benchmarks %>% 
  filter(variable %in% VARS) -> 
  ipcc_warm

ggplot() +
  geom_errorbar(data = ipcc_warm,
                aes(year, ymin = min, ymax = max),
                width=.2) +
  geom_point(data = hec_warm, aes(year, value, color = version), alpha = 0.75) + 
  geom_point(data = scm_warm, aes(year, value, color = source),
             shape = 4, position = position_jitter(height = 0, width = JW)) +  
  geom_point(data = ipcc_warm, aes(year, value, color = "ipcc ar6"), shape = 4) +
  facet_wrap("scenario", scales = "free") + 
  theme(axis.text.x = element_text(angle = 35, vjust = 0.6)) + 
  labs(y = NULL, x = NULL, title = "Future Warming (deg C)") + 
  scale_color_manual(values = COLORS.BENCHMARKS) + 
  theme(legend.title = element_blank()) -> 
  p; p

fname <- file.path(file.path(SUP_FIGS, "AR6"),  paste0("AR6_warming_.", TYPE))
ggsave(plot = p, filename = fname, width = WIDTH, height = HEIGHT)





